// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalApiContext))]
    [Migration("20230331165331_Update")]
    partial class Update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnimalName")
                        .HasColumnType("longtext");

                    b.Property<string>("DaysInShelter")
                        .HasColumnType("longtext");

                    b.Property<string>("Species")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            AnimalName = "Steve",
                            DaysInShelter = "5",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            AnimalName = "Molly",
                            DaysInShelter = "15",
                            Species = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            AnimalName = "Matilda",
                            DaysInShelter = "6",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 4,
                            AnimalName = "Lolly",
                            DaysInShelter = "22",
                            Species = "Cat"
                        },
                        new
                        {
                            AnimalId = 5,
                            AnimalName = "Greg",
                            DaysInShelter = "10",
                            Species = "Bunny"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
